apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: argocd-server-metrics
  labels:
    {{- include "monitoring-dashboards.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: "8083"
      path: /metrics
      interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server-metrics
  namespaceSelector:
    matchNames:
      - argocd
---
# ArgoCD Repo Server metrics
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: argocd-repo-server-metrics
  labels:
    {{- include "monitoring-dashboards.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: "8084"
      path: /metrics
      interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server-metrics
  namespaceSelector:
    matchNames:
      - argocd
---
# ArgoCD Application Controller metrics
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: argocd-application-controller-metrics
  labels:
    {{- include "monitoring-dashboards.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: "8082"
      path: /metrics
      interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-metrics
  namespaceSelector:
    matchNames:
      - argocd
