apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
spec:
  description: "postgresql of cluster challenge"
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  instances: 1
  startDelay: 30
  stopDelay: 30
  primaryUpdateStrategy: unsupervised
  
  enableSuperuserAccess: true
  superuserSecret:
    name: postgresql-superuser
  
  bootstrap:
    initdb:
      database: app
      owner: postgres

  storage:
    storageClass: local-path 
    size: 256Mi
  
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

  monitoring:
    enablePodMonitor: true


